# What is PyTorch?
PyTorch Tutorial [WHAT IS PYTORCH?](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py) 의 연습

In [2]:
from __future__  import print_function
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.7656e-42, 0.0000e+00],
        [0.0000e+00, 2.7530e+12, 0.0000e+00]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.3250, 0.4641, 0.2254],
        [0.2486, 0.9549, 0.8672],
        [0.2223, 0.4167, 0.7181],
        [0.1401, 0.9139, 0.8837],
        [0.2470, 0.8388, 0.1344]])


In [5]:
x = torch.zeros(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1605,  0.4920, -0.5415],
        [ 1.0184,  0.3271, -0.3433],
        [ 0.4409,  0.7647, -1.3912],
        [ 0.2268, -0.3518, -0.2147],
        [ 0.2457,  0.4043, -0.3728]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [14]:
y = torch.empty(x.size())
y.copy_(x)

tensor([[-0.1605,  0.4920, -0.5415],
        [ 1.0184,  0.3271, -0.3433],
        [ 0.4409,  0.7647, -1.3912],
        [ 0.2268, -0.3518, -0.2147],
        [ 0.2457,  0.4043, -0.3728]])

In [15]:
x.t_()

tensor([[-0.1605,  1.0184,  0.4409,  0.2268,  0.2457],
        [ 0.4920,  0.3271,  0.7647, -0.3518,  0.4043],
        [-0.5415, -0.3433, -1.3912, -0.2147, -0.3728]])

In [16]:
x.t_()

tensor([[-0.1605,  0.4920, -0.5415],
        [ 1.0184,  0.3271, -0.3433],
        [ 0.4409,  0.7647, -1.3912],
        [ 0.2268, -0.3518, -0.2147],
        [ 0.2457,  0.4043, -0.3728]])

In [29]:
print(x[:, 1]) # print n-th col in [m,1] shape
print(x[:, 1:]) # print from n-th col to the end 
print(x[:2]) # print until (n-1)th row

tensor([ 0.4920,  0.3271,  0.7647, -0.3518,  0.4043])
tensor([[ 0.4920, -0.5415],
        [ 0.3271, -0.3433],
        [ 0.7647, -1.3912],
        [-0.3518, -0.2147],
        [ 0.4043, -0.3728]])
tensor([[-0.1605,  0.4920, -0.5415],
        [ 1.0184,  0.3271, -0.3433]])


In [24]:
print(x[1,:]) # print n-th row
print(x[0:]) # print from n-th row to the end

tensor([ 1.0184,  0.3271, -0.3433])
tensor([[-0.1605,  0.4920, -0.5415],
        [ 1.0184,  0.3271, -0.3433],
        [ 0.4409,  0.7647, -1.3912],
        [ 0.2268, -0.3518, -0.2147],
        [ 0.2457,  0.4043, -0.3728]])


In [32]:
x = torch.randn(4, 4)
y = x.view(16) # "view" resize/ reshape the tensor
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions (In this case, 2 is inferred from 16/2)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [34]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8637])
0.8637431263923645


In [35]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# AUTOGRAD: AUTOMATIC DIFFERENTIATION

Pytorch tutorial [AUTOGRAD: AUTOMATIC DIFFERENTIATION](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py)의 연습

In [41]:
import torch

In [42]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [43]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [44]:
print(y.grad_fn)

In [49]:
z = y*y*3
out = z.mean()
print(x, y, z, out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True) tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [48]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


### Gradients

In [50]:
out.backward()

In [51]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [60]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x * 2
while y.data.norm() < 1000: # "y.data.norm()" calculates L2-norm of the tensor
    y = y * 2

print(y)

tensor([ 1.3600, -0.6064,  1.4680], requires_grad=True)
tensor([ 696.3353, -310.4575,  751.6277], grad_fn=<MulBackward0>)


In [61]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [62]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [68]:
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])
